swagger: "2.0"
info:
  title: necode/operatorservice/request_response.proto
  version: version not set
tags:
  - name: OperatorService
consumes:
  - application/json
produces:
  - application/json
paths: {}
definitions:
  enumsIndexedValueType:
    type: string
    enum:
      - INDEXED_VALUE_TYPE_UNSPECIFIED
      - INDEXED_VALUE_TYPE_TEXT
      - INDEXED_VALUE_TYPE_KEYWORD
      - INDEXED_VALUE_TYPE_INT
      - INDEXED_VALUE_TYPE_DOUBLE
      - INDEXED_VALUE_TYPE_BOOL
      - INDEXED_VALUE_TYPE_DATETIME
      - INDEXED_VALUE_TYPE_KEYWORD_LIST
    default: INDEXED_VALUE_TYPE_UNSPECIFIED
  operatorserviceAddOrUpdateRemoteClusterResponse:
    type: object
  operatorserviceAddSearchAttributesResponse:
    type: object
  operatorserviceClusterMetadata:
    type: object
    properties:
      clusterName:
        type: string
        description: Name of the cluster name.
      clusterId:
        type: string
        description: Id of the cluster.
      address:
        type: string
        description: Cluster accessible address.
      initialFailoverVersion:
        type: string
        format: int64
        description: A unique failover version across all connected clusters.
      historyShardCount:
        type: integer
        format: int32
        description: History service shard number.
      isConnectionEnabled:
        type: boolean
        description: A flag to indicate if a connection is active.
  operatorserviceDeleteNamespaceResponse:
    type: object
    properties:
      deletedNamespace:
        type: string
        description: Temporary namespace name that is used during reclaim resources step.
  operatorserviceListClustersResponse:
    type: object
    properties:
      clusters:
        type: array
        items:
          type: object
          $ref: '#/definitions/operatorserviceClusterMetadata'
        title: List of all cluster information
      nextPageToken:
        type: string
        format: byte
  operatorserviceListSearchAttributesResponse:
    type: object
    properties:
      customAttributes:
        type: object
        additionalProperties:
          $ref: '#/definitions/enumsIndexedValueType'
        description: Mapping between custom (user-registered) search attribute name to its IndexedValueType.
      systemAttributes:
        type: object
        additionalProperties:
          $ref: '#/definitions/enumsIndexedValueType'
        description: Mapping between system (predefined) search attribute name to its IndexedValueType.
      storageSchema:
        type: object
        additionalProperties:
          type: string
        description: Mapping from the attribute name to the visibility storage native type.
  operatorserviceRemoveRemoteClusterResponse:
    type: object
  operatorserviceRemoveSearchAttributesResponse:
    type: object
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
